### ISSUE TITLE
Git Task 404

### ISSUE THREAD

**Issue by chriscerk** [naveego/bosun#4]
command: `b git task 137 "Version Browser Date Sort" -m "Fields are currently sorted by the date.{attributeId}.keyword in elastic, whichfails on dates"`

result: `GET https://api.github.com/repos/repos/frontends/milestones: 404 Not Found []`

Looks like `repos/repos` is not a correct URI, but not sure why the git client would get this

**Comment by derekssmith** [comment]
I just ran into this also.  I believe it is due to bosun assuming you are running in a go project path.  I am looking into it.

**Comment by derekssmith** [comment]
I learned that bosun requires a convention for your project files to be in `org/repo` name format.  I fought this a little bit, mostly because I didn't want bosun telling me how to name my files. :)   However, this is a good thing!  Consistency is good!
